### ISSUE TITLE
EditMode Preview not showing

### ISSUE THREAD

**Issue by vyscond** [astuetz/PagerSlidingTabStrip#186]
It's just me or the library itself don't produce previews on the Android Studio editor? That would be really useful to have a preview, but it's an awesome lib anyways! Thanks for sharing!!!

**Comment by ajans** [comment]
I think it's not possible to directly show any preview in the editor, since the PagerSlidingTabStrip needs some data about ViewPager-items and their titles, which comes from either a PagerAdapter or its subclasses FragmentPagerAdapter / FragmentStatePagerAdapter.

What you could do, is, you could extend PagerSlidingTabStrip and override its 3-argument-constructor, probably something like this (didnt test this):

    public class MyPagerSlidingTabStrip extends com.astuetz.PagerSlidingTabStrib {
        public MyPagerSlidingTabStrip(Context context, AttributeSet attrs, int defStyle) {
            super(context, attrs, defStyle);
            if (isInEditMode()) {
                // init fake viewpager and page-adapter and call setViewPager with them
            }
        }
    }
